id = "aquarium-theme"
name = "Aquarium Theme"
version = "0.6.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "A colorful, dark, cozy Zed port of the Aquarium theme."
repository = "https://github.com/biaqat/aquarium-theme-zed"
